- name: Virtual host is configured
  become: yes
  become_user: root
  template:
    src: "{{ nginx_file_source }}"
    dest: "{{ nginx_file_dest }}"
    owner: "{{ backend_user }}"
    group: "{{ backend_user }}"

- name: proxy params are configured
  become: yes
  become_user: root
  template:
    src: "{{ nginx_proxy_params_src }}"
    dest: "{{ nginx_proxy_params_dest }}"
    owner: "{{ backend_user }}"
    group: "{{ backend_user }}"

- name: Web server is restarted
  service:
    name: nginx
    state: restarted
    enabled: yes