- name: Latest software installed for nginx 
    yum:
      name: "{{ nginx_packages }}"
      state: present

- name: Web server is started and enabled
    service:
      name: nginx
      state: started
      enabled: yes

