backend_user: "kpidpu"
backend_path: "/opt/chucknorris/backend"
backend_venv_path: "{{ backend_path }}/venv"

# Package src and dest
# NOTE: Github auth required to download wheel. So for now just expexting a the wheel to be in energy.statuspage/ansible/playbooks/files/energy_status_page.whl
#backend_wheel_url: "https://github.deutsche-boerse.de/dev/energy.statuspage/releases/download/v0.1.1/energy_status_page-0.1.1-py3-none-any.whl"
backend_wheel_local_src_path: "files/chucknorris-1.0.0-py3-none-any.whl"

backend_wheel_dest_path: "{{ backend_path }}/chucknorris-1.0.0-py3-none-any.whl"
backend_config_path: "{{ backend_path }}/postgres.ini"


#docker_file
docker_file_source: "files/docker"
docker_file_dest: "{{ backend_path }}/docker"

#start script
start_file_source: "files/start.sh"
start_file_dest: "{{ backend_path }}/start.sh"


