- name: Install Container requires
  become: yes
  become_user: root
  ignore_errors: yes
  yum:
    name:
      - podman
      - skopeo
      - buildah
    state: present
  notify: deploy_docker_file

- name: Check for existence of index.html
  stat:
    path: "{{ docker_file_dest }}/docker"
  register: docker_stats

- name: Go to the folder
  command: chdir={{ backend_path }} 

- name: build a python image 
  become: yes
  become_user: root
  command: podman build --tag chuck -f docker
  register: container_result
  when:
    - docker_stats.stats.exists
   
- name: Show stdout from the previous task.
  debug:
    msg: "STDOUT from previous task: {{ item.stdout }}"
  loop: "{{ container_result['results'] }}"
 

