- name: Install Container requires
  become: yes
  become_user: root
  yum:
    name:
      - podman
      - skopeo
      - buildah
    state: present

- name: Pull latest image
  command: podman pull latest
  register: image_result
   
- name: Show stdout from the previous task.
  debug:
    msg: "STDOUT from previous task: {{ item.stdout }}"
  loop: "{{ image_result['results'] }}"

- name: Pull latest image
  command: podman run --name=rhel registry.access.redhat.com/rhel /bin/bash
  register: image_result

- name: Show stdout from the previous task.
  debug:
    msg: "STDOUT from previous task: {{ item.stdout }}"
  loop: "{{ podman_result['results'] }}"

