- name: Install Container requires
  become: yes
  become_user: root
  ignore_errors: yes
  yum:
    name:
      - podman
      - skopeo
      - buildah
    state: present

- name: Pull latest image
  command: podman pull latest
  register: image_result
   
- name: Show stdout from the previous task.
  debug:
    var: image_result

- name: start the container image
  command: podman run --name=rhel registry.access.redhat.com/rhel /bin/bash
  register: container_result

- name: Show stdout from the previous task.
  debug:
    var: container_result

- name: show the podman
  command: podman ps -a
