- name: Stop backend
  import_tasks: stop.yml
  tags: stop

- name: Install backend
  import_tasks: install.yml
  tags: install

- name: deploy container
  import_tasks: install_container.yml
  tags: container

- name: Start backend
  import_tasks: start.yml
  tags: start


