- name: Clean all images 
  become: true
  become_user: root
  command: podman rmi -a -f

- name: Clean all containers
  become: true
  become_user: root
  command: podman system prune --all --force

- name: check all images 
  become: true
  become_user: root
  command: podman images

- name: check all containers
  become: true
  become_user: root
  command: podman ps -a

    
