- name: start the python container
  become: true
  become_user: root
  command: podman run -dit  --net=host --name=python localhost/chuck /bin/bash
  register: container_result

- name: Show stdout from the previous task.
  debug:
    var: container_result

- name: show the podman
  command: podman ps -a

- name: start the application in container(chuckmoris&web)
  become: true
  become_user: root
  shell: ./start.sh > /dev/null
  args:
    chdir: "{{ backend_path }}"
  register: chuckmoris_result


- name: check if the applications are running in container(chuckmoris&web)
  become: true
  become_user: root
  shell: podman exec python ps aux
  register: chuckmoris_result_app

- name:
  debug:
    var: chuckmoris_result_app


- name: check if the jokes are written to the file
  become: true
  become_user: root
  shell: podman exec python cat jokes.txt
  register: chuckmoris_result_jokes

- name:
  debug:
    var: chuckmoris_result_jokes