- name: start the rhel container
  become: true
  become_user: root
  command: podman run -dit  --net=host --name=python localhost/chuck /bin/bash
  register: container_result

- name: Show stdout from the previous task.
  debug:
    var: container_result

- name: show the podman
  command: podman ps -a

- name: start the application in container(chuckmoris&web)
  become: true
  become_user: root
  shell: ./start.sh > /dev/null
  args:
    chdir: "{{ backend_path }}"
  register: chuckmoris_result

