- name: start the rhel container
  become: true
  become_user: root
  command: podman run -dit  --net=host --name=python localhost/chuck /bin/bash
  register: container_result

- name: Show stdout from the previous task.
  debug:
    var: container_result

- name: show the podman
  command: podman ps -a

- name: start the backend in container(chuckmoris)
  become: true
  become_user: root
  command: podman exec python run_chucknorris
  register: chuckmoris_result

- name: start the webapp in container
  become: true
  become_user: root
  command: podman exec python run_web
  register: webserver_result