backend_user: "user1"

# Package src and dest
# NOTE: Github auth required to download wheel. So for now just expexting a the wheel to be in energy.statuspage/ansible/playbooks/files/energy_status_page.whl
#backend_wheel_url: "https://github.deutsche-boerse.de/dev/energy.statuspage/releases/download/v0.1.1/energy_status_page-0.1.1-py3-none-any.whl"

#httpd 
nginx_file_source: "files/py-app.j2"
nginx_file_dest: "/etc/nginx/conf.d/py-app"

## httpd_packages
nginx_packages:
  - nginx
  - mod_ssl


